### ISSUE TITLE
Organização de conteúdo por Nível e Idioma

### ISSUE THREAD

**Issue by nazarepiedady** [Vue-js-Angola/awesome-list-vue-angola#4]
A lista é bem interessante no ponto de vista de conteúdo, mas a ordem é confusa. Acredito se dividir-mos os conteúdos por arquivos e pastas onde a estrutura das pastas poderia ser algo do tipo:

* languange:
  * English:
     * Beginner (conteúdo introdutório sobre Vue.js)
     * Intermediate (conteúdo intermédiario sobre Vue.js e projectos para prática de leitura de código escrito por outros)
     * Advanced (conteúdo avançado sobre Vue.js, boas práticas no uso da tecnólogia)
  * Portuguese:
    * Iniciante
    * Intermédiario
    * Avançado
 
Aqui o arquivo readme servirá apenas de índice para cada seção de conteúdo, segundo o ídioma e nível.

**Comment by martygo** [comment]
Muito obrigado pela recomendação. Vamos trabalhar nisso,
